all:
	g++ ./Objects/Triangle.cpp ./Objects/Instance.cpp ./Utils/Camera.cpp ./Utils/Vect3.cpp ./Utils/Matrix.cpp ./Utils/Normal.cpp ./Utils/Point3.cpp ./Builder/TriangleWorld.cpp ./Builder/World.cpp ./pngWriter/lodepng.cpp main.cpp -pthread -O3 -std=c++11 -o raytracer

